version: '3.8'

services:
  # Main application
  digicraft-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: digicraft-app-simple
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    container_name: digicraft-postgres-simple
    restart: unless-stopped
    environment:
      - POSTGRES_DB=digicraft
      - POSTGRES_USER=digicraft_user
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
