version: '3.8'

services:
  digicraft-app:
    build: .
    ports:
      - "${APP_PORT:-6060}:6060"
    container_name: digicraft-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
