name: Deploy React App to EC2

on:
  push:
    branches:
      - main   # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
        run: |
          echo "🚀 Deploying to EC2 server..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            sudo mkdir -p /var/www/digicraft-space &&
            sudo chown -R $USER:$USER /var/www/digicraft-space
          "
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/digicraft-space/

      - name: Restart Apache
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl restart apache2 && echo '✅ Apache restarted successfully'"
