name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main   # change if you deploy from another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: cd client && npm install

      - name: Build Vite App
        run: cd client && npm run build

      - name: Configure SSH
        run: |
          mkdir -p $HOME/.ssh
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Deploy to EC2 via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./client/dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/react-app/
